import React, { ReactNode } from 'react';
import Head from 'next/head';
import Header from './Header';

interface Props {
    children:ReactNode,
    title: string
}

const Layout:React.FC<Props> = ({children, title}) => {
    return(
        <div>
            <Head>
                <title>{` Real Yield Demo| ${title} `}</title>
                <meta name='description' content='Generated by create next app'/>
                <link rel='icon' href='/favicon.ico'/>
            </Head>
            <main>
                <Header/>
                <div className='px-1 sm:px-3 md:px-5 lg:px-1 xl:px-1 2xl:px-8'>
                    {children}
                </div>
            </main>
        </div>
    )
}

export default Layout;