import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../components/Header'
import Farm from '../components/Stake'
import HeroArticle from '../components/View/HeroArticle'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Farm />
      {/*<Header/>
      <div className='hero px-20 flex flex-wrap items-center justify-between h-full w-full'>
      <div className="left  my-5 lg:my-3 w-full lg:w-[45%] xl:w-[45%]">
        <HeroArticle />
      </div>
      <div className="right w-full lg:w-[50%]">
          <img
          className='h-full w-full'
          src='/staking.png'
          alt=' Illustration showing staking Money' />
        </div>
  </div>*/}
    </>
  )
}
